'use client';

import { createContext, useContext, useState, ReactNode, useCallback, useEffect } from 'react';

export type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translations dictionary
const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Upload screen
    'upload.title': 'Strava Wrapped',
    'upload.subtitle': 'Ton année 2025 en mouvement',
    'upload.humor': "Strava n'aime pas que vous jouiez avec vos données. On va les libérer.",
    'upload.dropzone': 'Importe ton export Strava',
    'upload.instruction': 'Glisse-dépose ou clique pour sélectionner ton fichier ZIP',
    'upload.fileType': 'Fichier ZIP uniquement • Max 2 Go',
    'upload.privacy': '🔒 100% privé : tout le traitement se fait dans ton navigateur. Tes données ne quittent jamais ton appareil.',
    'upload.loading': 'Analyse de tes exploits...',
    'upload.extracting': 'Extraction des données du ZIP en cours',
    'upload.wait': 'Cela peut prendre quelques secondes pour les gros fichiers',
    'upload.processing': 'Traitement en cours...',
    'upload.pleaseWait': 'Merci de patienter',
    'upload.error.zipOnly': 'Merci de télécharger votre export Strava au format ZIP',
    'upload.error.tooLarge': 'Le fichier doit faire moins de 2 Go',

    // Tutorial
    'tutorial.howTo': 'Comment obtenir ton export Strava :',
    'tutorial.step1': 'Connecte-toi sur',
    'tutorial.step2': 'Dans "Télécharger ou supprimer votre compte", clique sur',
    'tutorial.step2Link': 'Demander un export',
    'tutorial.step3': 'Reçois le lien de téléchargement par email (<3 min)',
    'tutorial.step4': 'Télécharge le fichier .zip et importe-le ici',

    // Common
    'common.tapToContinue': 'Tap pour continuer',
    'common.activities': 'activités',
    'common.km': 'km',
    'common.hours': 'h',
    'common.morning': 'Matin',
    'common.midday': 'Midi',
    'common.afternoon': 'Après-midi',
    'common.evening': 'Soirée',
    'common.night': 'Nuit',

    // Slide titles
    'slide.intro.title': 'Tableau de Bord',
    'slide.intro.subtitle': 'Ton année en chiffres',
    'slide.intro.activities': 'Activités',
    'slide.intro.activitiesDesc': 'exploits réalisés',
    'slide.intro.distance': 'Distance',
    'slide.intro.distanceDesc': 'kilomètres parcourus',
    'slide.intro.elevation': 'Dénivelé +',
    'slide.intro.elevationDesc': 'mètres de dénivelé',
    'slide.intro.message1': '2025 n\'était pas une année',
    'slide.intro.message2': 'C\'était une épopée.',
    'slide.intro.swipeToContinue': 'Swipe pour continuer',
    'slide.dominance.title': 'Ton Profil Athlétique',
    'slide.identity.title': 'Identité',
    'slide.identity.certifiedAthlete': 'Athlète Certifié',
    'slide.identity.hello': 'Salut',
    'slide.identity.readyForRecap': 'Prêt pour le récap',
    'slide.identity.ofYourEpicIn': 'de ton épopée à',
    'slide.identity.tapToStart': 'Tap pour commencer',
    'slide.breakdown.title': 'Activités',
    'slide.breakdown.subtitle': 'Répartition par type',
    'slide.breakdown.diversity': 'Diversité',
    'slide.breakdown.activityTypes': 'types d\'activités',
    'slide.breakdown.tapToContinue': 'Tap pour continuer',
    'slide.elevation.title': 'Le Grimpeur',
    'slide.elevation.subtitle': 'Dénivelé positif conquis',
    'slide.elevation.elevationGain': 'Dénivelé +',
    'slide.elevation.metersClimbed': 'mètres grimpés',
    'slide.elevation.equivalentTo': 'Équivalent à',
    'slide.elevation.message': 'Chaque montée est une victoire',
    'slide.elevation.tapToContinue': 'Tap pour continuer',
    'slide.chronosMonth.title': 'Rythme Annuel',
    'slide.chronosMonth.subtitle': 'Ton année mois par mois',
    'slide.chronosMonth.mostActive': 'Ton mois le plus actif',
    'slide.chronosDay.title': 'Rythme Hebdo',
    'slide.chronosDay.subtitle': 'Tes jours préférés',
    'slide.chronos.title': 'Chronos',
    'slide.chronos.subtitle': 'Quand vous bougez',
    'slide.chronos.favoriteTime': 'Ton créneau préféré',
    'slide.weather.title': 'Guerrier Météo',
    'slide.weather.subtitle': 'Toutes conditions, toute l\'année',
    'slide.kudos.title': 'Le Chasseur de Kudos',
    'slide.kudos.subtitle': 'Ta popularité en 2025',
    'slide.kudos.kudosReceived': 'kudos reçus',
    'slide.kudos.onActivities': 'Sur',
    'slide.kudos.activitiesShared': 'activités partagées',
    'slide.kudos.comments': 'commentaire',
    'slide.kudos.commentsPlural': 'commentaires',
    'slide.kudos.encouragement': 'd\'encouragement',
    'slide.kudos.legendCommunity': 'Légende de la communauté',
    'slide.kudos.risingStar': 'Star montante',
    'slide.kudos.encouragementChamp': 'Champion d\'encouragement',
    'slide.kudos.tapToContinue': 'Tap pour continuer',
    'slide.social.title': 'Social Butterfly',
    'slide.social.subtitle': 'Ta communauté Strava',
    'slide.social.followers': 'Followers',
    'slide.social.challenges': 'Défis 2025',
    'slide.social.comments': 'Commentaires',
    'slide.social.completedOf': 'Complétés sur',
    'slide.social.publishedOn': 'Publiés sur Strava',
    'slide.social.community': 'Ta communauté Strava grandit et te soutient',
    'slide.consistency.title': 'Régularité',
    'slide.consistency.subtitle': 'Construire l\'habitude',
    'slide.consistency.recordStreak': 'Série Record',
    'slide.consistency.consecutiveDays': 'jours consécutifs',
    'slide.consistency.currentStreak': 'Série Actuelle',
    'slide.consistency.days': 'jours',
    'slide.consistency.activeDays': 'Jours Actifs',
    'slide.consistency.activeDaysOfYear': 'jours actifs sur l\'année',
    'slide.consistency.totalWeeksActive': 'Total Semaines Actives',
    'slide.consistency.weeks': 'sem.',
    'slide.consistency.disciplineChamp': 'Champion de la discipline',
    'slide.consistency.habitMakesStrength': 'L\'habitude fait la force',
    'slide.consistency.keepItUp': 'Continuez sur cette lancée',
    'slide.consistency.tapToContinue': 'Tap pour continuer',
    'slide.records.title': 'Hall of Fame',
    'slide.records.subtitle': 'Tes Records Personnels',
    'slide.records.noRecords': 'Aucun Record Disponible',
    'slide.records.uploadMore': 'Uploadez plus d\'activités pour voir vos records',
    'slide.records.longestDistance': 'Plus Longue Distance',
    'slide.records.longestDuration': 'Plus Longue Durée',
    'slide.records.fastestActivity': 'Activité la Plus Rapide',
    'slide.records.globalAverageSpeed': 'Vitesse Moyenne Globale',
    'slide.records.averagePerformance': 'Performance moyenne sur toutes tes activités',
    'slide.records.tapToContinue': 'Tap pour continuer',

    'slide.summary.title': 'Ton Année 2025',
    'slide.summary.incredibleYear': 'Année Incroyable!',
    'slide.summary.wrapped': 'Wrapped 2025',
    'slide.summary.totalActivities': 'Activités Totales',
    'slide.summary.trainingTime': 'Temps d\'Entraînement',
    'slide.summary.hours': 'hrs',
    'slide.summary.favoriteActivity': 'Activité Préférée',
    'slide.summary.times': 'fois',
    'slide.summary.restart': 'Recommencer',
    'slide.summary.keepMoving': 'Continuez à bouger. Continuez à vous surpasser.',
    'slide.summary.seeYouIn2026': 'Rendez-vous en 2026!',
    'slide.summary.shareTitle': 'Mon Strava Wrapped 2025',
    'slide.summary.shareText': 'Mon récap Strava 2025',
    'slide.summary.exportError': 'Erreur lors de l\'export de l\'image',

    'slide.intensity.title': 'Zones Cardiaques',
    'slide.intensity.subtitle': 'Distribution de ton intensité',
    'slide.intensity.dominantZone': 'Zone dominante',
    'slide.intensity.spentInZone': 'Passé {percentage}% du temps dans cette zone',
    'slide.intensity.tapToContinue': 'Tap pour continuer',

    'slide.power.title': 'La Puissance',
    'slide.power.subtitle': 'Watts générés en 2025',
    'slide.power.peakPower': 'Pic Maximum',
    'slide.power.watts': 'watts',
    'slide.power.mostPowerfulOutput': 'sortie la plus puissante',
    'slide.power.averagePower': 'Puissance Moyenne',
    'slide.power.onAllRidesWithSensor': 'sur toutes les sorties avec capteur',
    'slide.power.powerData': 'Données de puissance',
    'slide.power.activitiesWithSensor': 'activités avec capteur',
    'slide.power.electrifying': 'Électrisant',
    'slide.power.tapToContinue': 'Tap pour continuer',

    'slide.gravity.title': 'La Gravité',
    'slide.gravity.subtitle': 'Vous avez défié la descente',
    'slide.gravity.negativeElevation': 'Dénivelé Négatif',
    'slide.gravity.metersOfDescent': 'mètres de descente',
    'slide.gravity.kneesImpacts': 'Vos genoux ont survécu à',
    'slide.gravity.equivalentImpacts': 'impacts équivalents',
    'slide.gravity.jointsDeserveMedal': 'Vos articulations méritent une médaille',
    'slide.gravity.tapToContinue': 'Tap pour continuer',

    'slide.trail.title': 'Facteur Trail',
    'slide.trail.subtitle': 'Vous avez quitté le bitume',
    'slide.trail.ofDistanceOnTrails': 'de votre distance sur les sentiers',
    'slide.trail.badgeUnlocked': 'Badge débloqué',
    'slide.trail.trailMaster': 'Maître des Sentiers',
    'slide.trail.trailExplorer': 'Explorateur de Sentiers',
    'slide.trail.trailCurious': 'Curieux des Sentiers',
    'slide.trail.bornForTrails': 'Vous êtes né(e) pour les sentiers',
    'slide.trail.natureCalls': 'La nature vous appelle',
    'slide.trail.keepExploring': 'Continuez d\'explorer',
    'slide.trail.tapToContinue': 'Tap pour continuer',

    'slide.calorie.title': 'Le Carburant',
    'slide.calorie.subtitle': 'Calories brûlées en 2025',
    'slide.calorie.kcalBurned': 'kcal brûlées',
    'slide.calorie.onActivities': 'Sur {count} activité{activityWord} ({percentage}% du total)',
    'slide.calorie.activity': '',
    'slide.calorie.activities': 's',
    'slide.calorie.equivalent': 'Équivalent',
    'slide.calorie.croissants': 'croissants',
    'slide.calorie.bakeryThanks': 'La boulangerie te remercie',
    'slide.calorie.tapToContinue': 'Tap pour continuer',

    'slide.moteur.title': 'Le Moteur',
    'slide.moteur.subtitle': 'Tes paramètres de performance',
    'slide.moteur.ftpThreshold': 'Seuil de Puissance (FTP)',
    'slide.moteur.maxHeartRate': 'Fréquence Cardiaque Max',
    'slide.moteur.bpm': 'bpm',
    'slide.moteur.averagePowerInActivity': 'Puissance moyenne en activité',
    'slide.moteur.mostFrequentZones': 'Zones cardiaques les plus fréquentes',
    'slide.moteur.calibratedForPerformance': 'Machine calibrée pour la performance',
    'slide.moteur.tapToContinue': 'Tap pour continuer',

    'slide.emoji.title': 'Humeur en Émojis',
    'slide.emoji.subtitle': 'Vos activités racontées en symboles',
    'slide.emoji.emotionsInMotion': 'Vos émotions en mouvement',
    'slide.emoji.tapToContinue': 'Tap pour continuer',

    'slide.dominance.detectedProfile': 'Profil détecté',
    'slide.dominance.preparingRecap': 'Préparation de ton récap...',

    'slide.socialSlide.title': 'Social Butterfly',
    'slide.socialSlide.subtitle': 'Ton réseau en 2025',
    'slide.socialSlide.messagesSent': 'Messages Envoyés',
    'slide.socialSlide.conversations': 'conversations',
    'slide.socialSlide.clubsJoined': 'Clubs Rejoints',
    'slide.socialSlide.communities': 'communautés',
    'slide.socialSlide.socialIndex': 'Indice Social',
    'slide.socialSlide.superConnected': 'Super connecté',
    'slide.socialSlide.wellIntegrated': 'Bien intégré',
    'slide.socialSlide.networkGrowing': 'Réseau en croissance',
    'slide.socialSlide.connectedToCommunity': 'Connecté à la communauté',
    'slide.socialSlide.tapToContinue': 'Tap pour continuer',

    'slide.addict.title': 'L\'Accro',
    'slide.addict.subtitle': 'Tes habitudes Strava en 2025',
    'slide.addict.logins': 'connexions',
    'slide.addict.in2025': 'en 2025',
    'slide.addict.peakHour': 'Heure de Pic',
    'slide.addict.earlyBird': 'Lève-tôt',
    'slide.addict.afternoon': 'Après-midi',
    'slide.addict.evening': 'Soirée',
    'slide.addict.nightOwl': 'Noctambule',
    'slide.addict.favoriteDay': 'Jour Favori',
    'slide.addict.mostActiveDay': 'ton jour le plus actif',
    'slide.addict.confirmedAddict': 'Accro confirmé',
    'slide.addict.veryRegular': 'Très régulier',
    'slide.addict.moderatelyConnected': 'Connecté modéré',
    'slide.addict.tapToContinue': 'Tap pour continuer',
  },
  en: {
    // Upload screen
    'upload.title': 'Strava Wrapped',
    'upload.subtitle': 'Your 2025 in Motion',
    'upload.humor': "Strava doesn't like you playing with your data. Let's free it.",
    'upload.dropzone': 'Import your Strava export',
    'upload.instruction': 'Drag & drop or click to select your ZIP file',
    'upload.fileType': 'ZIP file only • Max 2 GB',
    'upload.privacy': '🔒 100% private: all processing happens in your browser. Your data never leaves your device.',
    'upload.loading': 'Analyzing your achievements...',
    'upload.extracting': 'Extracting ZIP data',
    'upload.wait': 'This may take a few seconds for large files',
    'upload.processing': 'Processing...',
    'upload.pleaseWait': 'Please wait',
    'upload.error.zipOnly': 'Please upload your Strava export as a ZIP file',
    'upload.error.tooLarge': 'File must be less than 2 GB',

    // Tutorial
    'tutorial.howTo': 'How to get your Strava export:',
    'tutorial.step1': 'Log in to',
    'tutorial.step2': 'In "Download or Delete Your Account", click',
    'tutorial.step2Link': 'Request Your Archive',
    'tutorial.step3': 'Receive download link via email (<3 min)',
    'tutorial.step4': 'Download the .zip file and import it here',

    // Common
    'common.tapToContinue': 'Tap to continue',
    'common.activities': 'activities',
    'common.km': 'km',
    'common.hours': 'h',
    'common.morning': 'Morning',
    'common.midday': 'Midday',
    'common.afternoon': 'Afternoon',
    'common.evening': 'Evening',
    'common.night': 'Night',

    // Slide titles
    'slide.intro.title': 'Dashboard',
    'slide.intro.subtitle': 'Your year in numbers',
    'slide.intro.activities': 'Activities',
    'slide.intro.activitiesDesc': 'achievements completed',
    'slide.intro.distance': 'Distance',
    'slide.intro.distanceDesc': 'kilometers covered',
    'slide.intro.elevation': 'Elevation +',
    'slide.intro.elevationDesc': 'meters of elevation',
    'slide.intro.message1': '2025 wasn\'t a year',
    'slide.intro.message2': 'It was an epic.',
    'slide.intro.swipeToContinue': 'Swipe to continue',
    'slide.dominance.title': 'Your Athletic Profile',
    'slide.identity.title': 'Identity',
    'slide.identity.certifiedAthlete': 'Certified Athlete',
    'slide.identity.hello': 'Hello',
    'slide.identity.readyForRecap': 'Ready for the recap',
    'slide.identity.ofYourEpicIn': 'of your epic in',
    'slide.identity.tapToStart': 'Tap to start',
    'slide.breakdown.title': 'Activities',
    'slide.breakdown.subtitle': 'Breakdown by type',
    'slide.breakdown.diversity': 'Diversity',
    'slide.breakdown.activityTypes': 'activity types',
    'slide.breakdown.tapToContinue': 'Tap to continue',
    'slide.elevation.title': 'The Climber',
    'slide.elevation.subtitle': 'Elevation gain conquered',
    'slide.elevation.elevationGain': 'Elevation +',
    'slide.elevation.metersClimbed': 'meters climbed',
    'slide.elevation.equivalentTo': 'Equivalent to',
    'slide.elevation.message': 'Every climb is a victory',
    'slide.elevation.tapToContinue': 'Tap to continue',
    'slide.chronosMonth.title': 'Annual Rhythm',
    'slide.chronosMonth.subtitle': 'Your year month by month',
    'slide.chronosMonth.mostActive': 'Your most active month',
    'slide.chronosDay.title': 'Weekly Rhythm',
    'slide.chronosDay.subtitle': 'Your favorite days',
    'slide.chronos.title': 'Chronos',
    'slide.chronos.subtitle': 'When you move',
    'slide.chronos.favoriteTime': 'Your favorite time',
    'slide.weather.title': 'Weather Warrior',
    'slide.weather.subtitle': 'All conditions, all year',
    'slide.kudos.title': 'The Kudos Hunter',
    'slide.kudos.subtitle': 'Your 2025 popularity',
    'slide.kudos.kudosReceived': 'kudos received',
    'slide.kudos.onActivities': 'On',
    'slide.kudos.activitiesShared': 'shared activities',
    'slide.kudos.comments': 'comment',
    'slide.kudos.commentsPlural': 'comments',
    'slide.kudos.encouragement': 'of encouragement',
    'slide.kudos.legendCommunity': 'Community legend',
    'slide.kudos.risingStar': 'Rising star',
    'slide.kudos.encouragementChamp': 'Encouragement champion',
    'slide.kudos.tapToContinue': 'Tap to continue',
    'slide.social.title': 'Social Butterfly',
    'slide.social.subtitle': 'Your Strava community',
    'slide.social.followers': 'Followers',
    'slide.social.challenges': 'Challenges 2025',
    'slide.social.comments': 'Comments',
    'slide.social.completedOf': 'Completed out of',
    'slide.social.publishedOn': 'Published on Strava',
    'slide.social.community': 'Your Strava community grows and supports you',
    'slide.consistency.title': 'Consistency',
    'slide.consistency.subtitle': 'Building the habit',
    'slide.consistency.recordStreak': 'Record Streak',
    'slide.consistency.consecutiveDays': 'consecutive days',
    'slide.consistency.currentStreak': 'Current Streak',
    'slide.consistency.days': 'days',
    'slide.consistency.activeDays': 'Active Days',
    'slide.consistency.activeDaysOfYear': 'active days of the year',
    'slide.consistency.totalWeeksActive': 'Total Weeks Active',
    'slide.consistency.weeks': 'wks.',
    'slide.consistency.disciplineChamp': 'Discipline champion',
    'slide.consistency.habitMakesStrength': 'Habit makes strength',
    'slide.consistency.keepItUp': 'Keep it up',
    'slide.consistency.tapToContinue': 'Tap to continue',
    'slide.records.title': 'Hall of Fame',
    'slide.records.subtitle': 'Your Personal Records',
    'slide.records.noRecords': 'No Records Available',
    'slide.records.uploadMore': 'Upload more activities to see your records',
    'slide.records.longestDistance': 'Longest Distance',
    'slide.records.longestDuration': 'Longest Duration',
    'slide.records.fastestActivity': 'Fastest Activity',
    'slide.records.globalAverageSpeed': 'Global Average Speed',
    'slide.records.averagePerformance': 'Average performance across all your activities',
    'slide.records.tapToContinue': 'Tap to continue',

    'slide.summary.title': 'Your 2025',
    'slide.summary.incredibleYear': 'Incredible Year!',
    'slide.summary.wrapped': 'Wrapped 2025',
    'slide.summary.totalActivities': 'Total Activities',
    'slide.summary.trainingTime': 'Training Time',
    'slide.summary.hours': 'hrs',
    'slide.summary.favoriteActivity': 'Favorite Activity',
    'slide.summary.times': 'times',
    'slide.summary.restart': 'Restart',
    'slide.summary.keepMoving': 'Keep moving. Keep surpassing yourself.',
    'slide.summary.seeYouIn2026': 'See you in 2026!',
    'slide.summary.shareTitle': 'My Strava Wrapped 2025',
    'slide.summary.shareText': 'My Strava 2025 recap',
    'slide.summary.exportError': 'Error exporting image',

    'slide.intensity.title': 'Heart Rate Zones',
    'slide.intensity.subtitle': 'Your intensity distribution',
    'slide.intensity.dominantZone': 'Dominant zone',
    'slide.intensity.spentInZone': 'Spent {percentage}% of time in this zone',
    'slide.intensity.tapToContinue': 'Tap to continue',

    'slide.power.title': 'Power',
    'slide.power.subtitle': 'Watts generated in 2025',
    'slide.power.peakPower': 'Peak Power',
    'slide.power.watts': 'watts',
    'slide.power.mostPowerfulOutput': 'most powerful output',
    'slide.power.averagePower': 'Average Power',
    'slide.power.onAllRidesWithSensor': 'on all rides with sensor',
    'slide.power.powerData': 'Power data',
    'slide.power.activitiesWithSensor': 'activities with sensor',
    'slide.power.electrifying': 'Electrifying',
    'slide.power.tapToContinue': 'Tap to continue',

    'slide.gravity.title': 'Gravity',
    'slide.gravity.subtitle': 'You defied the descent',
    'slide.gravity.negativeElevation': 'Negative Elevation',
    'slide.gravity.metersOfDescent': 'meters of descent',
    'slide.gravity.kneesImpacts': 'Your knees survived',
    'slide.gravity.equivalentImpacts': 'equivalent impacts',
    'slide.gravity.jointsDeserveMedal': 'Your joints deserve a medal',
    'slide.gravity.tapToContinue': 'Tap to continue',

    'slide.trail.title': 'Trail Factor',
    'slide.trail.subtitle': 'You left the pavement',
    'slide.trail.ofDistanceOnTrails': 'of your distance on trails',
    'slide.trail.badgeUnlocked': 'Badge unlocked',
    'slide.trail.trailMaster': 'Trail Master',
    'slide.trail.trailExplorer': 'Trail Explorer',
    'slide.trail.trailCurious': 'Trail Curious',
    'slide.trail.bornForTrails': 'You were born for the trails',
    'slide.trail.natureCalls': 'Nature calls you',
    'slide.trail.keepExploring': 'Keep exploring',
    'slide.trail.tapToContinue': 'Tap to continue',

    'slide.calorie.title': 'The Fuel',
    'slide.calorie.subtitle': 'Calories burned in 2025',
    'slide.calorie.kcalBurned': 'kcal burned',
    'slide.calorie.onActivities': 'On {count} {activityWord} ({percentage}% of total)',
    'slide.calorie.activity': 'activity',
    'slide.calorie.activities': 'activities',
    'slide.calorie.equivalent': 'Equivalent',
    'slide.calorie.croissants': 'croissants',
    'slide.calorie.bakeryThanks': 'The bakery thanks you',
    'slide.calorie.tapToContinue': 'Tap to continue',

    'slide.moteur.title': 'The Engine',
    'slide.moteur.subtitle': 'Your performance parameters',
    'slide.moteur.ftpThreshold': 'Power Threshold (FTP)',
    'slide.moteur.maxHeartRate': 'Max Heart Rate',
    'slide.moteur.bpm': 'bpm',
    'slide.moteur.averagePowerInActivity': 'Average power in activity',
    'slide.moteur.mostFrequentZones': 'Most frequent heart rate zones',
    'slide.moteur.calibratedForPerformance': 'Machine calibrated for performance',
    'slide.moteur.tapToContinue': 'Tap to continue',

    'slide.emoji.title': 'Emoji Mood',
    'slide.emoji.subtitle': 'Your activities told in symbols',
    'slide.emoji.emotionsInMotion': 'Your emotions in motion',
    'slide.emoji.tapToContinue': 'Tap to continue',

    'slide.dominance.detectedProfile': 'Detected profile',
    'slide.dominance.preparingRecap': 'Preparing your recap...',

    'slide.socialSlide.title': 'Social Butterfly',
    'slide.socialSlide.subtitle': 'Your network in 2025',
    'slide.socialSlide.messagesSent': 'Messages Sent',
    'slide.socialSlide.conversations': 'conversations',
    'slide.socialSlide.clubsJoined': 'Clubs Joined',
    'slide.socialSlide.communities': 'communities',
    'slide.socialSlide.socialIndex': 'Social Index',
    'slide.socialSlide.superConnected': 'Super connected',
    'slide.socialSlide.wellIntegrated': 'Well integrated',
    'slide.socialSlide.networkGrowing': 'Network growing',
    'slide.socialSlide.connectedToCommunity': 'Connected to the community',
    'slide.socialSlide.tapToContinue': 'Tap to continue',

    'slide.addict.title': 'The Addict',
    'slide.addict.subtitle': 'Your Strava habits in 2025',
    'slide.addict.logins': 'logins',
    'slide.addict.in2025': 'in 2025',
    'slide.addict.peakHour': 'Peak Hour',
    'slide.addict.earlyBird': 'Early bird',
    'slide.addict.afternoon': 'Afternoon',
    'slide.addict.evening': 'Evening',
    'slide.addict.nightOwl': 'Night owl',
    'slide.addict.favoriteDay': 'Favorite Day',
    'slide.addict.mostActiveDay': 'your most active day',
    'slide.addict.confirmedAddict': 'Confirmed addict',
    'slide.addict.veryRegular': 'Very regular',
    'slide.addict.moderatelyConnected': 'Moderately connected',
    'slide.addict.tapToContinue': 'Tap to continue',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('fr');
  const [isClient, setIsClient] = useState(false);

  // Load from localStorage on mount (client-side only)
  useEffect(() => {
    setIsClient(true);
    if (typeof window !== 'undefined') {
      const savedLang = localStorage.getItem('stravawrapped_language') as Language;
      if (savedLang && (savedLang === 'fr' || savedLang === 'en')) {
        setLanguageState(savedLang);
      }
    }
  }, []);

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    // Persist to localStorage
    if (typeof window !== 'undefined') {
      localStorage.setItem('stravawrapped_language', lang);
    }
  }, []);

  // Translation function
  const t = useCallback((key: string): string => {
    return translations[language][key] || key;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
